# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhoneValidation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhoneValidation
pod 'libPhoneNumber-iOS', '~> 0.8'


end
